### ISSUE TITLE
error RUNNING ot_model.compute_all_transport_maps() 

### ISSUE THREAD

**Issue by zacharylau10** [broadinstitute/wot#20]
hi,
    when I run the tutorial with the example, `ot_model.compute_all_transport_maps()` produce an error 

> TypeError: transport_stable_learn_growth() missing 1 required positional argument: 'scaling_iter'

I find that there is no default value of `scaling_iter` in `transport_stable_learn_growth()`. but when I adding 3000 to `scaling_iter`, another error emergence

> ~/anaconda3/envs/zachary35/lib/python3.5/site-packages/wot/ot/optimal_transport.py in transport_stablev2(C, lambda1, lambda2, epsilon, scaling_iter, g, pp, qq, numInnerItermax, tau, epsilon0, extra_iter)
    277         # stabilization
    278         iterations_since_epsilon_adjusted += 1
--> 279         if (max(max(abs(a)), max(abs(b))) > tau):
    280             u = u + epsilon_i * np.log(a)
    281             v = v + epsilon_i * np.log(b)  # absorb

> TypeError: unorderable types: float() > NoneType()

My WOT version is 0.2.2.
Also, I noticed that WOT version 0.2.0 is ok when running `ot_model.compute_all_transport_maps()`.

Thankyou

**Comment by joshua-gould** [comment]
Thanks for reporting the bug. I just pushed a fix to pip. Please let me know if you run into additional issues.

**Comment by zacharylau10** [comment]
hi, 
    I update the WOT, but the error is still the same, and it seems like missing some default parameters. So I add some parameters 
`ot_model = wot.initialize_ot_model(matrix_file, days_file, growth_iters=1,
                                   scaling_iter=3000,tau=10000,epsilon0=1,max_threads=24,
                                   epsilon=.02, lambda1=10, lambda2=80, local_pca=0)` 
and 
`ot_model.compute_all_transport_maps()` 
and it will produce results, but downstream results will be different with the original results which in the simulated data folder.

    There is another error is produced by `vs = wot.commands.compute_validation_summary(ot_model)` which look like missing default parameters too. 
    
    it will be better if you could revised the tutorial of the simulated data. Thank you~

**Comment by joshua-gould** [comment]
I updated the code to use default parameters when called via the API and not the command line. Thanks.
