### ISSUE TITLE
AttributeError in census.py

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#55]
I have updated to version 1.0.1. Thanks for that.
When trying to run again the command line examples, I get an error, when trying to calculate the ancestor census. 

```
$wot census --tmap tmaps --cell_set cell_sets_scores.gmt --out census --day 4

Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/bin/wot", line 11, in <module>
    load_entry_point('wot', 'console_scripts', 'wot')()
  File "/home/yeroslaviz/projects/AnnB/TestingEnv/wot1.0.0/wot/wot/__main__.py", line 21, in main
    cmd.main(command_args)
  File "/home/yeroslaviz/projects/AnnB/TestingEnv/wot1.0.0/wot/wot/commands/census.py", line 28, in main
    timepoints, census = tmap_model.ancestor_census(cell_sets_matrix, *populations.values())
AttributeError: 'list' object has no attribute 'values'


```

**Comment by frymor** [comment]
Hi,
 I was wondering if there is any intentions of trying to fix the problems in the new version, or if you need more information to do so
thanks, Assa

**Comment by joshua-gould** [comment]
Fixed in master branch

**Comment by frymor** [comment]
The error is still there in version 1.0.2.

the command 
```
wot census --tmap tmaps1.0.2/tmaps1.0.2 --cell_set Output1.0.2/cell_sets_scores.gmt --out census --day 10
```
gives still the error
```
Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/bin/wot", line 10, in <module>
    sys.exit(main())
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/wot/__main__.py", line 21, in main
    cmd.main(command_args)
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/wot/commands/census.py", line 28, in main
    timepoints, census = tmap_model.ancestor_census(cell_sets_matrix, *populations.values())
AttributeError: 'list' object has no attribute 'values'
```

**Comment by geoffschieb** [comment]
What is the file cell_set_scores?
You need to give it a cell set file, not a signature score file.

**Comment by frymor** [comment]
the  `cell_set_scores.gmt` is the file resulting from calculating the cell sets from gene-set scores.
it's a gmt file and looks like that:

```
...
Cluster10_score -       p11_cortex_140_AACGTTGCACAGAGGT p11_cortex_140_AAGCCGCTCGTGGGAA p11_cortex_140_ACACTGAAGGAATCGC p11_cortex_140_ACAGCCGTCTCCAGGG p11_cortex_140_ACAGCTAAGGCTAGAC p11_cortex_140_ACATCAGAGGACAGCT p11_cortex_140_ACCAGTACATGCCCGA ...
Cluster11_score -       p6_cortex_137_AATCCAGTCCTTGACC  p6_cortex_137_ACACCAACAGGGATTG  p6_cortex_137_ACTTTCAAGTAACCCT  p6_cortex_137_AGAATAGTCTCGCTTG  p6_cortex_137_AGATTGCAGACTTGAA  p6_cortex_137_ATTACTCTCGTGGTCG  p6_cortex_137_CAGATCACAAGGACTG  ...
Cluster12_score -       p6_cortex_137_ATTATCCTCTGCCAGG  p6_cortex_137_GAGTCCGTCTGGTTCC  p6_cortex_137_GGTGAAGGTCCATCCT  p6_cortex_137_TCCACACGTGAGTGAC  p6_cortex_137_TGTGGTAGTCTCAACA  p11_cortex_140_AACACGTTCAGAGCTT p11_cortex_140_AATCCAGAGTCCTCCT p11_
cortex_140_AATCCAGCAGCCAATT     p11_cortex_140_ACACCGGGTGCCTGGT p11_cortex_140_ACATACGTCGTTTATC p11_cortex_140_ACTATCTAGTGTCCCG p11_cortex_140_ACTATCTCAGTGGGAT p11_cortex_140_ACTGATGGTTGCCTCT p11_cortex_140_AGCTTGAAGCTGAAAT ...
Cluster13_score -       p6_cortex_137_AACCGCGTCGTCTGAA  p6_cortex_137_AGAATAGGTCCTAGCG  p6_cortex_137_ATTCTACTCTCACATT  p6_cortex_137_ATTTCTGGTAAGTAGT  p6_cortex_137_CAGCAGCAGTCGATAA  p6_cortex_137_CGAGCCACACTCTGTC  p6_cortex_137_CGTGTAATCCGCGGTA  p6_cortex_137_CGTGTCTCAATAACGA      ...
...
```

**Comment by frymor** [comment]
the error message is gone. thanks for  the update
